version: '2'
services:
    db:
        build: ./db
        volumes:
            - ./db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'botchan'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'testtest'
            #MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "3306:3306"
