# mysql
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      maxLifetime: 80000
      idleTimeout: 40000
      leak-detection-threshold: 7000
      auto-commit: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
logging:
  level:
    jdbc: OFF
    sqltiming: DEBUG
hibernate:
  dialect:
    storage_engine: "innodb"

# line
line:
  bot:
    channelToken: ${LINE_BOT_CHANNEL_TOKEN}
    channelSecret: ${LINE_BOT_CHANNEL_SECRET}

# server
server:
  hostName: "sheltered-scrubland-23764.herokuapp.com"
