# mysql
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    hikari:
      leak-detection-threshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
      maxLifetime: 80000
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
logging:
  level:
    jdbc: OFF
    sqltiming: DEBUG
hibernate:
  dialect:
    storage_engine: "innodb"

# line
line:
  bot:
    channelToken: ${LINE_BOT_CHANNEL_TOKEN}
    channelSecret: ${LINE_BOT_CHANNEL_SECRET}

# server
server:
  hostName: "sheltered-scrubland-23764.herokuapp.com"
